baseURL = "/"
languageCode = "en-us"
title = "Paul Artjomow"
rssLimit = 20
minify = false
copyright = "2021 Paul Artjomow All rights reserved"

staticDir = ['static']

[Author]
  name = "Prixix"
  email = "me@prixix.com"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]
